# Generated by Django 3.2 on 2022-02-03 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=70, verbose_name='Skill')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail address')),
                ('resume', models.FileField(null=True, upload_to='uploads/', verbose_name='CV')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Profile photo')),
                ('headline', models.CharField(max_length=50, verbose_name='About')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='Company')),
                ('job_title', models.CharField(max_length=50, verbose_name='Job title')),
                ('localtion', models.CharField(max_length=50, verbose_name='Location')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('skills', models.ManyToManyField(blank=True, to='about.JobSkills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.user')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100, verbose_name='School/Institution')),
                ('degree', models.CharField(max_length=50, verbose_name='')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.user')),
            ],
        ),
    ]
