# Generated by Django 3.2 on 2022-02-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobskills',
            name='skill',
            field=models.CharField(max_length=70, unique=True, verbose_name='Skill'),
        ),
    ]
