# Generated by Django 3.2 on 2022-02-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_jobskills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=50, verbose_name='Degree'),
        ),
    ]
