# Generated by Django 3.2 on 2022-02-04 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='localtion',
            new_name='location',
        ),
    ]
